# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.shapelets.io
title: Shapelets
email: info@shapelets.io
author: The Grumpy Cat
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: '©2018 Shapelets. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/shapelets
  - title: github
    url: https://github.com/shapelets
  - title: linkedin
    url: https://www.linkedin.com/company/shapelets/
