# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.shapelets.io
title: Shapelets
image: 'img/ShapeletsLogo.png'
email: info@shapelets.io
author: The Grumpy Cat
description: > # "Write an awesome description for your new site here.
  Shapelets is an open source framework for time series analysis in big data environments. Easy to integrate with any database, high-performance (GPUs, CPU and multicore) and scalable.
copyright: '©2018 Shapelets. All Rights Reserved.'
credits: 'Contact: <a href="mailto:info@shapelets.io">info@shapelets.io</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/shapelets
  - title: github
    url: https://github.com/shapelets
  - title: linkedin
    url: https://www.linkedin.com/company/shapelets/
